import Head from 'next/head';
import Image from 'next/image';

import Banner from '../components/banner/Banner';
import Card from '../components/card/Card';
import styles from '../styles/Home.module.css';
import coffeStoresData from '../data/coffee-stores.json';
import { getImages } from '../services/unsplash';

export default function Home({ stores }) {
  const handleClick = () => {
    return null;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>My Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleClick={handleClick} />
        <div className={styles.heroImage}>
          <Image
            alt="hero-coffee-img"
            src="/static/hero-image.png"
            width={700}
            height={400}
          />
        </div>
        {stores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {stores.map((store) => {
                return (
                  <Card
                    key={store.id}
                    className={styles.card}
                    name={store.name}
                    imgUrl={store.imgUrl}
                    href={`/store/${store.id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  console.log('teste');
  return {
    props: {
      stores: coffeStoresData,
    }, //pass para o comp como prop
  };
}
